# docker-compose.yml
version: "3"
services:
  react-app:
    build: ./client
    depends_on:
      - api
    stdin_open: true
    ports:
      - "3000:3000"
#    command: npm start
    networks:
      - pern-app
  api:
    build: ./api
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://user:pass@postgres:5432/db
      NODE_ENV: development
      PORT: 8080
    ports:
      - "8080:8080"
#    command: npm run dev
    volumes:
      - .:/app/
      - /app/node_modules
    networks:
      - pern-app
  postgres:
    image: postgres:12
    ports:
      - "35432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
    networks:
      - pern-app
networks:
  pern-app:
    driver: bridge